environment:
  name: "wireguard_perfmon_test"
  location: "northamerica-northeast1"
  img_dest: "gcr.io/arctiq-data-lab/k6"

k6:
  duration: "30s"
  multiplier: "1" # Define how many synchronous k6 runs should execute
  vus: "1"

bigquery:
  dataset_name: "perftest_dataset"
  dataset_format: "NEWLINE_DELIMITED_JSON"
  table_name: "perftest_table"
  dataset_desc: "perftest"

gcs:
  bucket_name: "perfmon_test"
  file_name: "metrics.json"

