environment:
  name: "wireguard_perfmon_test"
  project_id: "greg-apigee-hybrid-eks" 
  location: "northamerica-northeast1"
  img_dest: "gcr.io/greg-apigee-hybrid-eks/k6"

k6:
  duration: "5m"
  multiplier: "8" # Define how many synchronous k6 runs should execute
  vus: "1000"

bigquery:
  dataset_name: "perftest_dataset"
  dataset_format: "NEWLINE_DELIMITED_JSON"
  table_name: "perftest_table"
  dataset_desc: "perftest"

gcs:
  bucket_name: "perfmon_test"
  file_name: "metrics.json"

