steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/k6:${_SHORT_SHA}'
      - '-f'
      - './image/Dockerfile'
      - './image/'
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker push gcr.io/${_PROJECT_ID}/k6:${_SHORT_SHA}
    id: push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/${_PROJECT_ID}/k6:${_SHORT_SHA}'
      - 'gcr.io/${_PROJECT_ID}/k6:latest'
substitutions:
  _PROJECT_ID: "greg-apigee-hybrid-eks"
  _SHORT_SHA: "ac3808a"
images:
  - 'gcr.io/${_PROJECT_ID}/k6:${_SHORT_SHA}'
  - 'gcr.io/${_PROJECT_ID}/k6:latest'
